### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by LaGr77** [pbatard/Fido#14]
I have Win10 without IE. Only Edge and Firefox. When I run FIDO.ps1, the process finish with error.

![Poznámka 2020-07-02 100325](https://user-images.githubusercontent.com/67732401/86333154-cca29e80-bc4b-11ea-9441-127668eb101d.png)

What can I do, to repair it.

**Comment by pbatard** [comment]
I am afraid that if you forcibly remove Windows components, then I can't provide a solution for you.

Vanilla/standard installations of Windows 10 come with Internet Explorer, and we need Internet Explorer for `Invoke-WebRequest` as the other methods of requesting web content from the Microsoft website will not do (Especially `Invoke-WebRequest -UseBasicParsing` can __NOT__ be used because it will not return the content we need to process).

You will need to go to _Turn Windows features on or off_ or go to _Apps & Features_ &rarrr; _Optional features_ to add Internet Explorer back. There is no other alternative.
