### ISSUE TITLE
Windows 10 20H2 missing

### ISSUE THREAD

**Issue by mehmetemin23** [pbatard/Fido#17]
Can you please add the windows 10 20H2 update to your script?

**Comment by pbatard** [comment]
Don't worry, I'm in the process of adding it. But I couldn't do it until Microsoft made it available from https://www.microsoft.com/en-gb/software-download/windows10ISO and they've only done that a couple of hours ago...

**Comment by pbatard** [comment]
For the record, the longest part of that process, once Microsoft have updated their ISO download site, is getting the full build number (which should be something like `19042.123`), as finding the SKU numbers to add is relatively easy (the one for 20H2 is `1807`, or `1805` for Edu), but then I need to go through a full ISO download and either create a Windows To Go drive or go through a full install so that I can get the actual build number...

**Comment by pbatard** [comment]
Done.

**Comment by mehmetemin23** [comment]
Thank you very much. I can help you with getting the actual build number in the feature. To make it a little bit easier for you.

**Comment by pbatard** [comment]
I appreciate that, but that shouldn't be necessary. It only takes a couple of hours to download the ISO and find the build number, and it helps me validate that the Windows To Go feature of Rufus still works with the new release.
