### ISSUE TITLE
Error using with Powershell 7

### ISSUE THREAD

**Issue by nnk95** [pbatard/Fido#19]
When using with Powershell 7.1.0 the following error is shown:

```ps
.\Fido.ps1
Please Wait...
Add-Type: Fido.ps1:66
Line |
  66 |  Add-Type -MemberDefinition $code -Namespace Gui -UsingNamespace "Syst …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | (18,16): error CS1069: The type name 'Icon' could not be found in the namespace 'System.Drawing'. This
     | type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral,
     | PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly.  public static Icon
     | ExtractIcon(string file, int number, bool largeIcon)                ^
```
No problems when using with Powershell 5.

**Comment by pbatard** [comment]
I fixed this, but it won't help much since Microsoft forcibly removed the ability to remove HTML parsing in PowerShell 7.x, which we need. So you won't be able to do much besides seeing the UI. See PowerShell/PowerShell#2867 as well as [this](https://stackoverflow.com/questions/60655737/how-to-parse-html-table-with-powershell-core-7).

I'm still not sure what the best option is going to be moving forward, as force installing a third party PowerShell component from a script that is meant to be small and run near instantaneously will completely diminish the user experience we've been going for, and that's not even talking about the need to inform the user about installing said 3rd party, which, unlike our script, we can't vet for.

We are going great length in Rufus to ensure that users can trust our Fido script, since we sign it with custom credentials and validate that the signature matches before executing it, and we spent a lot of time making sure that we didn't use anything that could throw this trust off... But now, Microsoft utter short-sightedness in not providing a default HTML parsing assembly when they decided to stop relying on IE is going to throw our whole security model in disarray, because there have been way too many examples of third party components being hijacked for malicious purposes to make us happy about trusting any of them...

So, great job here Microsoft... For a company who has allegedly built its customer base around making sure that you didn't break features that applications relied on, you have suddenly decided that this shouldn't apply to your PowerShell team, and rather than do the right thing, which was to provide an assembly that added the HTML parsing capabilities of IE, you just told all the users that relied on it to go f**k themselves.

Oh and the thing that someone at Microsoft may want to realize with regards to this whole situation in terms of security is that, if I had any interest in trying to compromise Windows machines, you bet that the first thing I'd do, on hearing that Microsoft decided not to bother with providing an HTML parser, is publish a seemingly innocuous HTML parsing library that would of course also include a bug or backdoor that I could exploit down the line... Real fine job here... 🤦
