### ISSUE TITLE
[Question] Windows edition ID

### ISSUE THREAD

**Issue by scriptingstudio** [pbatard/Fido#30]
Hello,
This is not an issue, your script works like a charm.
Could you please say where do you obtain the Windows edition ID ($winEditionId) from? That is a number after edition label.
```powershell
@(
   "21H2 (Build 19044.1288 - 2021.11)",
   @("Windows 10 Home/Pro/Edu", 2084),
   @("Windows 10 Home China ", ($zh + 2085))
),
```

**Comment by pbatard** [comment]
See #16.

I basically ran `techbench_dump.py 2000 2400 --json-indent 4 dump.json` and then looked at the generated JSON.

Note however that it's not because the `EditionId` exists that the download is available. For instance, `2084` and `2085` appeared more than one week ago, but the downloads for these ids were only made available yesterday.
