### ISSUE TITLE
Image version mismatch

### ISSUE THREAD

**Issue by scriptingstudio** [pbatard/Fido#31]
Hi there.
I was curious how to find versions of ISO images downloaded by `fido` script I tested to deploy OS and found strange things that image versions did not match the latest.

### Image download
```powershell
> Fido.ps1 -Win 10 -Lang ru
No release specified (-Rel). Defaulting to '21H2 (Build 19044.1288 - 2021.11)'.
No edition specified (-Ed). Defaulting to 'Windows 10 Home/Pro/Edu'.
No architecture specified (-Arch). Defaulting to 'x64'.
Selected: Windows 10 21H2 (Build 19044.1288 - 2021.11), Home/Pro/Edu, Russian, [x64]
Downloading 'Win10_21H2_Russian_x64.iso' (5,0 GB)...

> Fido.ps1 -Win 10 -Lang en
No release specified (-Rel). Defaulting to '21H2 (Build 19044.1288 - 2021.11)'.
No edition specified (-Ed). Defaulting to 'Windows 10 Home/Pro/Edu'.
No architecture specified (-Arch). Defaulting to 'x64'.
Selected: Windows 10 21H2 (Build 19044.1288 - 2021.11), Home/Pro/Edu, English, [x64]
Downloading 'Win10_21H2_English_x64.iso' (5,0 GB)...
```

### Expected Version
The script reports that the expected version would be `19044.1288`.

### Downloaded image information
```powershell
> Get-WindowsImage -ImagePath "C:\Software\Windows\wiso\sources\install.wim" -name 'Windows 10 Pro'

ImageIndex       : 4
ImageName        : Windows 10 Pro
ImageDescription : Windows 10 Pro
ImageSize        : 15 022 256 793 bytes
WIMBoot          : False
Architecture     : x64
Hal              :
Version          : 10.0.19041.1288
SPBuild          : 1288
SPLevel          : 0
EditionId        : Professional
InstallationType : Client
ProductType      : WinNT
ProductSuite     : Terminal Server
SystemRoot       : WINDOWS
DirectoryCount   : 27649
FileCount        : 101885
CreatedTime      : 06-10-2021 16:45:34
ModifiedTime     : 06-10-2021 21:10:49
Languages        : ru-RU (Default)

> Get-WindowsImage -ImagePath "C:\Software\Windows\wiso\sources\install.wim" -name 'Windows 10 Pro'

ImageIndex       : 6
ImageName        : Windows 10 Pro
ImageDescription : Windows 10 Pro
ImageSize        : 15 071 438 212 bytes
WIMBoot          : False
Architecture     : x64
Hal              :
Version          : 10.0.19041.1288
SPBuild          : 1288
SPLevel          : 0
EditionId        : Professional
InstallationType : Client
ProductType      : WinNT
ProductSuite     : Terminal Server
SystemRoot       : WINDOWS
DirectoryCount   : 26760
FileCount        : 99385
CreatedTime      : 06-10-2021 17:06:00
ModifiedTime     : 06-10-2021 21:22:01
Languages        : en-US (Default)
```

DISM app and Get-WindowsImage report the same: `19041.1288`.
Versions obtained by `MediaCreationTool21H2.exe` are `19044.1288`.
The same is correct for Windows 11 as well.
For temporarily I had to switch back to MediaCreationTool.

### offtopic
A little optimization.
`Invoke-WebRequest` shows a progress bar by default (for each byte). But it takes TOO much time.
Hiding a progress bar significantly reduces overall runtime.
```powershell
$progressPreference = 'silentlyContinue'
```

**Comment by pbatard** [comment]
`19044.1288` is what Windows reports when you run it and use `ver` or the System Information tool.

You can create a Windows To Go USB from the downloaded ISOs, or install Windows, and validate that for yourself.

As far as I am know, what `Get-WindowsImage`  and DISM report is __not__ based on the actual version of the Windows kernel from the image, but some other version info that is __NOT__ set correctly by Microsoft when they master the image. What you do end up with however is `19044.1288`, so you should __not__ take what `Get-WindowsImage`  and `dism` report for retail ISOs at face value.

Or, if you have an issue with this, and considering that (as you can easily validate through the SHA-1) the Windows 10 21H2 ISOs that Fido downloads are exactly the same as the ISOs you get from https://www.microsoft.com/en-us/software-download, then you should open an issue with Microsoft and let them know that they are not setting the version of their `install.wim` accurately, as, since neither Fido or Rufus alter the `19044.1288` images provided by Microsoft in any way, the issue is purely with them.

As to hiding the progress bar, I may add an option to do that, but that'll be low priority.
