### ISSUE TITLE
Windows 10 Enterprise

### ISSUE THREAD

**Issue by rbcrack** [pbatard/Fido#35]
Thank you for the script is it possible to ad Enterprise Edtion as it only allows for Home/Pro/Edu

**Comment by pbatard** [comment]
Microsoft does not appear to provide __public__ links to Enterprise editions of Windows (outside of insider builds), so, as long as it remains the case, it is not possible to add Enterprise downloads.

Basically, as you can see [here](https://www.microsoft.com/en-us/software-download/windows10) (after clicking on _More download options_):

> Sign in to the [Volume Licensing Service Center](https://www.microsoft.com/licensing/servicecenter/default.aspx) to download Enterprise editions.

So, Enterprise editions are only officially accessible behind the VL portal, and therefore cannot be provided by Fido.

**Comment by xbjfk** [comment]
Technically* there is a way to access enterprise versions without authentication.
Download products.cab:
latest Windows 11: https://go.microsoft.com/fwlink?linkid=2156292
latest Windows 10: https://go.microsoft.com/fwlink/?LinkId=841361
with googling you can find old version

extract the products.cab file from the url
inside there is a products.xml
browse products.xml for your desired edition, arch, etc.
download it
note since it will be ESD, you have to use DISM to convert to ISO (google how to do this)

*with a lot of effort in a way impractical for Fido

**Comment by luky92** [comment]
Actually if the only thing you need is a product key which i think is the
case you can use KMS product key which is publicly available in Microsoft's
docs

W dniu pon., 22.08.2022 o 09:03 Reagan ***@***.***>
napisał(a):

**Comment by luky92** [comment]
Also you can download it from here
https://www.microsoft.com/en-us/evalcenter/download-windows-10-enterprise
directly
It says evaluation but it's the same iso you just need a key to activate it
later

W dniu pon., 22.08.2022 o 09:05 Łukasz Klatka ***@***.***>
napisał(a):

**Comment by xbjfk** [comment]
I'm pretty sure eval, after 30 days, will shut down every hour, unlike the ESD which is not the evaluation version
