### ISSUE TITLE
Failed to retrieve architecures from server when ran using a Polish locale

### ISSUE THREAD

**Issue by luky92** [pbatard/Fido#37]
In GUI mode you get an error Error: Failed to retrive architectures from server

**Comment by luky92** [comment]
My machine
Windows 11 Pro 21h2 22000.556 Polish
What version I'm trying to download:
Win 10 21h2 polish x64 19044.1288

**Comment by luky92** [comment]
For some reason it works now

**Comment by pbatard** [comment]
Actually, I can replicate your issue when running Rufus in Polish and invoking Fido from there (but not when running Rufus in English). So it seems that when the script is being run from a Polish locale, there might be a parsing issue. I'll see if I can figure why that happens.

**Comment by pbatard** [comment]
Aaand, I can't replicate the issue any more...

Looks like Microsoft must have been updating their download server content, which triggered occasional download issues, because consecutive tests using the exact same settings are producing different outcome, and I don't really see that architecture error occurring unless we're getting a garbled or invalid reply from the servers.

I will therefore close this issue for now, and will reopen it if we start seeing this issue again on a more persistent basis.
