### ISSUE TITLE
Cumbersome lzma

### ISSUE THREAD

**Issue by T3rm1** [pbatard/Fido#39]
It was really cumbersome to unpack the release script. Had to install a program just for that. I'd say most people have WinRAR installed and it does not support it.
Would be a lot easier if you used a more common compression algorithm. Why not just deflate?

**Comment by pbatard** [comment]
Because of the first sentence of the Readme, that states:

> Fido is a PowerShell script that is primarily designed to be used in [Rufus](https://github.com/pbatard/rufus)

The use of LZMA is a design decision that is associated with what the script is __actually__ designed for, which is to be downloaded by Rufus. 

Also the fact that you see a download counter that currently reads 52 million downloads (though not all of these are actually for the script itself) should give you a hint that I really want to use a compression algorithm that is better than deflate, regardless of whether you think that maybe I shouldn't care about a download that is hosted by GitHub (because I'm pretty sure users in remote parts of the world with shitty internet connections do care).

Finally, the "Releases" you see are actually not intended to be used by the general public, but by Rufus (because then Rufus can easily pick an LZMA compressed script based on a tag). If you want the script, just use the 'raw' uncompressed file, which is the same as what you get in the LZMA, and which GitHub will happily provide you with at https://raw.githubusercontent.com/pbatard/Fido/master/Fido.ps1.

Closed as: You are misunderstanding the design goals behind this project, which is and will always be designed for Rufus automated usage first and foremost.

**Comment by T3rm1** [comment]
> I really want to use a compression algorithm that is better than deflate, regardless of whether you think that maybe I shouldn't care about a download that is hosted by GitHub (because I'm pretty sure users in remote parts of the world with shitty internet connections do care).

First of all, thanks for taking the time to explain this. I did indeed misunderstand the design goal.
However, I must say that someone who plans to download a full ISO from Microsoft probably won't mind loading 1056 bytes more for a deflate compressed file. :wink:

**Comment by pbatard** [comment]
That would be a valid point if part of the process to decide whether Rufus should present the download button to the user or not is to check if the lzma is downloadable or not, which should normally not produce an actual download of the file, but which can't be guaranteed in all internet configurations (e.g. caching and whatnot).

Plus I want to keep an option to move away from GitHub if needed, where using a better compression algorithm than deflate (without having to update Rufus) could be very handy. I've already had to hop servers once in a hurry, so anything that can help with a potential move is welcome.

I'll finish by adding what I refrained from pointing out earlier, which I was really tempted to dismiss your request with, which is that if you don't have 7-zip installed on Windows, there's something very wrong with your default Windows configuration... 😉
