### ISSUE TITLE
Windows 11 22H2 download error: (400) Bad Request.

### ISSUE THREAD

**Issue by liblaf** [pbatard/Fido#45]
When I tried to download Windows 11 22H2, I got the following output:

```console
Selected: Windows 11 22H2 (Build 22621.382 - 2022.09), Home/Pro/Edu, English International, [x64]
Error: The remote server returned an error: (400) Bad Request.
```

It seems to be a problem with remote server, not download script. It works fine when downloading 21H2.

**Comment by pbatard** [comment]
Yeah, I'm seeing the same issue.

From my latest dump.json, it looks like Microsoft have (silently? At least I've not heard anything about it yet) re-released Windows 11 22H2 with a __new__ `Windows 11 22H2_v1` SKU, and somehow broke downloads for the old SKU. Oh and they also released Windows 10 22H2.

here's the latest data (with `2360` the SKU we currently use in the script):
```json
    "2360": {
        "name": "Windows 11 22H2",
        "languages": {
            "14889": "Arabic",
            "14890": "Brazilian Portuguese",
            "14891": "Bulgarian",
            "14893": "Chinese (Simplified)",
            "14894": "Chinese (Traditional)",
            "14895": "Croatian",
            "14896": "Czech",
            "14897": "Danish",
            "14898": "Dutch",
            "14899": "English",
            "14900": "English International",
            "14901": "Estonian",
            "14902": "Finnish",
            "14903": "French",
            "14904": "French Canadian",
            "14905": "German",
            "14906": "Greek",
            "14907": "Hebrew",
            "14908": "Hungarian",
            "14909": "Italian",
            "14910": "Japanese",
            "14911": "Korean",
            "14912": "Latvian",
            "14913": "Lithuanian",
            "14914": "Norwegian",
            "14915": "Polish",
            "14916": "Portuguese",
            "14917": "Romanian",
            "14918": "Russian",
            "14919": "Serbian Latin",
            "14920": "Slovak",
            "14921": "Slovenian",
            "14922": "Spanish",
            "14923": "Spanish (Mexico)",
            "14924": "Swedish",
            "14925": "Thai",
            "14926": "Turkish",
            "14927": "Ukrainian"
        }
    },
    "2361": {
        "name": "Windows 11 22H2 Home China",
        "languages": {
            "14892": "Chinese (Simplified)"
        }
    },
(...)
    "2370": {
        "name": "Windows 11 22H2_v1",
        "languages": {
            "14955": "Arabic",
            "14956": "Brazilian Portuguese",
            "14957": "Bulgarian",
            "14959": "Chinese (Simplified)",
            "14960": "Chinese (Traditional)",
            "14961": "Croatian",
            "14962": "Czech",
            "14963": "Danish",
            "14964": "Dutch",
            "14965": "English",
            "14966": "English International",
            "14967": "Estonian",
            "14968": "Finnish",
            "14969": "French",
            "14970": "French Canadian",
            "14971": "German",
            "14972": "Greek",
            "14973": "Hebrew",
            "14974": "Hungarian",
            "14975": "Italian",
            "14976": "Japanese",
            "14977": "Korean",
            "14978": "Latvian",
            "14979": "Lithuanian",
            "14980": "Norwegian",
            "14981": "Polish",
            "14982": "Portuguese",
            "14983": "Romanian",
            "14984": "Russian",
            "14985": "Serbian Latin",
            "14986": "Slovak",
            "14987": "Slovenian",
            "14988": "Spanish",
            "14989": "Spanish (Mexico)",
            "14990": "Swedish",
            "14991": "Thai",
            "14992": "Turkish",
            "14993": "Ukrainian"
        }
    },
    "2371": {
        "name": "Windows 11 22H2_v1 Home China",
        "languages": {
            "14958": "Chinese (Simplified)"
        }
    },
(...)
    "2377": {
        "name": "Windows 10 22H2",
        "languages": {
            "15001": "Arabic",
            "15002": "Brazilian Portuguese",
            "15003": "Bulgarian",
            "15005": "Chinese (Simplified)",
            "15006": "Chinese (Traditional)",
            "15007": "Croatian",
            "15008": "Czech",
            "15009": "Danish",
            "15010": "Dutch",
            "15011": "English",
            "15012": "English International",
            "15013": "Estonian",
            "15014": "Finnish",
            "15015": "French",
            "15016": "French Canadian",
            "15017": "German",
            "15018": "Greek",
            "15019": "Hebrew",
            "15020": "Hungarian",
            "15021": "Italian",
            "15022": "Japanese",
            "15023": "Korean",
            "15024": "Latvian",
            "15025": "Lithuanian",
            "15026": "Norwegian",
            "15027": "Polish",
            "15028": "Portuguese",
            "15029": "Romanian",
            "15030": "Russian",
            "15031": "Serbian Latin",
            "15032": "Slovak",
            "15033": "Slovenian",
            "15034": "Spanish",
            "15035": "Spanish (Mexico)",
            "15036": "Swedish",
            "15037": "Thai",
            "15038": "Turkish",
            "15039": "Ukrainian"
        }
    },
    "2378": {
        "name": "Windows 10 22H2 Home China",
        "languages": {
            "15004": "Chinese (Simplified)"
        }
    }
}
```
If you replace `2360` by `2370` in the script, you'll find that you can download the Windows 11 22H2 v1 ISO without issue, so obviously, I'm going to update the script to add the v1 downloads, as well as the Windows 10 22H2 ones.

However, before I can do that, I need to validate the actual build number from `Win11_22H2_EnglishInternational_x64v1.iso`, which means I need to wait for my download to complete...

I'm also not sure what the deal is with 22H2_v0 and whether I should still keep it in my list if it doesn't work. From where we stand, it sure looks like Microsoft are trying to brush it under the carpet and pretend it never existed...

**Comment by pbatard** [comment]
Hmmm, somehow I'm getting the same error when trying to download Windows 10 22H2.

But, considering that https://www.microsoft.com/en-gb/software-download/windows10ISO still does not have a download for 22H2 (It still only lists _Windows 10 November 2021 Update_) and that we're early Sunday, which it typical time for ~~breaking~~ updating servers, I'm going to assume/hope that what we're seeing are transitional errors that have to do with Microsoft reshuffling their downloads...

**Comment by pbatard** [comment]
Please try the newly released Fido 1.35. It should work again when choosing `22H2 v1 (Build 22621.525 - 2022.10)`.

Note that I have not removed `22H2 (Build 22621.382 - 2022.09)` yet, as I am waiting to see if Microsoft will restore these downloads to ever work again...

**Comment by pbatard** [comment]
From what I can see, Microsoft had to produce the 22621.525 22H2 v1 because they screwed up the localisation of their setup files. I guess v1 is v0 with [KB5019311](https://support.microsoft.com/en-au/topic/september-27-2022-kb5019311-os-build-22621-525-out-of-band-a8967b98-df0e-4b70-af3b-6c0160666df3) applied on top:
> Addresses localization issues for some setup files. These issues might stop you from creating installation media for non-English languages.

**Comment by aggieNick02** [comment]
I commented on the commit that fixed this, but just to add the same here - indeed, Windows 11 22H2 v0 seems to have been nuked from existence. Not even a paid MSDN/Visual Studio subscription will get you access to it.

Interestingly, this isn't the first time a Windows RTM ISO has been dropped from the Visual Studio subscribers downloads. It happened with windows 10 1607. With that one though, you could still get it via the public-facing windows download page on Macs, etc: https://superuser.com/questions/1236687/where-can-i-find-the-original-non-slipstreamed-windows-10-1607-retail-en-us-is

Sadly, there doesn't seem to be a reasonable way to get 11 22H2 v0.

**Comment by pbatard** [comment]
Yup, that's why I removed it in fac4c492624b34c915f4782e9e77cf47893ac8e1

>  there doesn't seem to be a reasonable way to get 11 22H2 v0.

What's the point of getting v0 when v1 = v0 + [KB5019311](https://support.microsoft.com/en-au/topic/september-27-2022-kb5019311-os-build-22621-525-out-of-band-a8967b98-df0e-4b70-af3b-6c0160666df3) and not having KB5019311 may prevent you from being able to install altogether for non-En. Is there something specific to v0 that v1 doesn't have?

**Comment by aggieNick02** [comment]
> What's the point of getting v0 when v1 = v0 + [KB5019311](https://support.microsoft.com/en-au/topic/september-27-2022-kb5019311-os-build-22621-525-out-of-band-a8967b98-df0e-4b70-af3b-6c0160666df3) and not having KB5019311 may prevent you from being able to install altogether for non-En. Is there something specific to v0 that v1 doesn't have?

I should have elaborated on that. In the past, there have been issues present in the "updated" versions of an OS release that were not present in the RTM version. In Windows 10 1607, something changed in the updated ISOs that made attempts to remove appx apps fail in the updated ISOs even though it worked fine in the RTM ISO.

I'm hitting a kinda-related appx issue with Win 11 22H2, and it leaves me wondering if I'd hit with the RTM ISO. It's a bit corner-case, but it would be nice to be able to try it.

Plus, just from a preservationist standpoint, the idea that the RTM that everyone used for at least several days was just removed from existence by Microsoft is... odd.

**Comment by aggieNick02** [comment]
I should add - I think it would be completely reasonable for fido and/or rufus to not list a release if it was problematic. It's Microsoft's deletion of it completely, even from their paid archives of everything they've released, that's head-scratching.

**Comment by pbatard** [comment]
> the idea that the RTM that everyone used for at least several days was just removed from existence by Microsoft is... odd.

Not if, apparently, it was so poorly mastered that it prevented non English people from being able to install Windows altogether.

I'm with Microsoft on this, especially as I have done silent updates of Rufus releases in the past when there was a major bug: There's no way I'd want to leave a known broken release available and then have to waste time telling people, who decided to use a version of software that is known to have a ___major__ issue, that they should try with a more up to date version especially if, against all odds, they seem to be under the impression that somehow an older version of the software will somehow work better for them...

**Comment by aggieNick02** [comment]
> Not if, apparently, it was so poorly mastered that it prevented non English people from being able to install Windows altogether.

The wording in [KB5019311](https://support.microsoft.com/en-au/topic/september-27-2022-kb5019311-os-build-22621-525-out-of-band-a8967b98-df0e-4b70-af3b-6c0160666df3) is vague enough that the problem could range from a small number of users using less popular languages is affected, or anyone that doesn't want to install English is wasting their time. I wasn't able to find anything more concrete...

Also, there's significant differences between a faulty Rufus and a faulty Windows RTM that was available for at least a solid week. One big one is that Rufus's source is on github, while Windows is closed source. Microsoft removing the RTM is similar in effect to a force push on the Rufus github repo.

If the bug in the RTM was a really severe one, I could understand limiting access and putting up warnings before allowing downloads. But just erasing it from existence, given the duration of time it was released and the number of downloads it received, goes too far imho.

**Comment by pbatard** [comment]
> Microsoft removing the RTM is similar in effect to a force push on the Rufus github repo.

Which, as a developer, I have done countless times (granted in usually less than a 24 hour frame, but as a developer, being able to erase obvious mistakes from existence, if they have been discovered in a short enough timeframe, does make a lot of sense.

So, in the absence of any concrete data to support your _assertion_ that maybe the bug wasn't that bad, as a developer, and even as I really think that Microsoft should (or at least used to) have a testing department that is comprehensive enough to detect these kind of issues before they make their way onto the end users, I'm going to side with Microsoft that, yes, whatever issue v0 had was bad enough to warrant its removal from existence. Or it could also be that Microsoft had a major security flaw that they did not want to publicly disclose, which can also happen,  in which case the removal of the ISO would also be warranted to prevent bad actors from being able to easily access and exploit it.

The only fact we have is that we don't know what exactly the issue was, and, as such, and as much as it may be difficult, we have to _trust_ that the people who decided to remove the v0 ISO made the right call, and that, if we had the same information as they do, we would probably have done the same too.

Anything else is just pointless speculation.

**Comment by aggieNick02** [comment]
> > Microsoft removing the RTM is similar in effect to a force push on the Rufus github repo.
> 
> Which, as a developer, I have done countless times (granted in usually less than a 24 hour frame, but as a developer, being able to erase obvious mistakes from existence, if they have been discovered in a short enough timeframe, does make a lot of sense.
> 
>Or it could also be that Microsoft had a major security flaw that they did not want to publicly disclose, which can also happen, in which case the removal of the ISO would also be warranted to prevent bad actors from being able to easily access and exploit it.

I suppose anything's possible. But that seems rather unlikely.

Microsoft has removed v0 ISOs previously too. I wasn't trying to start an argument, but rather be helpful and provide evidence that the answer to your question:

>
> 
> The only fact we have is that we don't know what exactly the issue was, and, as such, and as much as it may be difficult, we have to _trust_ that the people who decided to remove the v0 ISO made the right call, and that, if we had the same information as they do, we would probably have done the same too.
> 
> Anything else is just pointless speculation.

**Comment by aggieNick02** [comment]
>  Or it could also be that Microsoft had a major security flaw that they did not want to publicly disclose, which can also happen, in which case the removal of the ISO would also be warranted to prevent bad actors from being able to easily access and exploit it.

I suppose anything's possible. But that seems rather unlikely. And pretty speculative.

Microsoft has removed v0 ISOs previously too (Win10 1607). I wasn't trying to start an argument, but rather just be helpful and provide evidence that the answer to your comment:

> I am waiting to see if Microsoft will restore these downloads to ever work again...

was almost certainly no, as they've removed the v0 from paid-only access too.

Microsoft has removed a v0 before (Win 10 1607). I don't think we "have to _trust_" that they made the right call then or now.  Of course it is their call to make. But the call could have been an accident, a policy (any updates within 2 weeks of RTM automatically result in replacing RTM with the update), or extremely intentional. We don't know.

**Comment by pbatard** [comment]
> I don't think we "have to trust" that they made the right call then or now.

I'd really like to hear your alternative then. Do you plan to go to Redmond with a lit torch and a picthfork, because your _guts_ (rather than an actual __reliable__ source of information) tells you that Microsoft _must_ have done something wrong here?

Also why should anyone trust _your_ outsider judgement more than Microsoft's here?

So, again, unless you are privy to information that you haven't shared with us, the best course of action (and please bear in mind that I am not saying that it is warranted, just that, in the absence of any other data, it's really the only sensible course of action to take) is to trust the Microsoft had valid reason to remove v0, __precisely__ because we don't have the full picture.

Otherwise, if you're going to question every single action taken by corporations, you might as well live in a cave, because there is no way that you can trust that, for instance, the PSU from your computer is not going to electrocute you or that the gas tank on the car you drive is not going to blow up after a small collision. By no mean does that imply that the trust is always well placed (Ford Pinto anyone?), just that, unless you're not planning to get into a car ever, the reasonable course of action, __in the absence of data to the contrary__, is to trust that the gas tank from the car you drive was designed not to burst in flame that easily... and that Microsoft had some good reason to remove v0.
