### ISSUE TITLE
Possible language issues

### ISSUE THREAD

**Issue by scriptingstudio** [pbatard/Fido#51]
1. `Switch` type parameter is aleady has value of `$false` by default. 
2. I would suggest to rename `disableprogress` to `noprogress`.
3. `$verbose` is common parameter for advanced functions. Defining explicit `$verbose` will result in conflict if you may want to introduce `[CmdletBinding()]` attribute later.
```powershell
function t {
	[CmdletBinding()]
	param (
		[switch]$verbose
	)
}

t -verbose

t : A parameter with the name 'Verbose' was defined multiple times for the command.
At line:10 char:1
+ t -verbose
+ ~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterNameAlreadyExistsForCommand
```

**Comment by pbatard** [comment]
1. There are some some reasons to want to make explicit variable initialisation for people who read the code (and are not privvy to PowerShell's idiosyncrasies).
2. I'm not going to rename that option. I think 'disable' is more explicit than 'no' and it really boils down to a matter of personal preferences.
3. Don't care. My interest with Fido is pretty much exclusively for use in Rufus. I **may** throw a bone to commandline users here and there, but that's about as far as I'm gonna get. My development time is too limited to want to make Fido a beacon of what PowerShell scripts should look like. As a matter of fact, I would have much preferred if someone took it upon themselves to create their own commandline version of Fido __and maintain it__, because it would have set the expectations straight with regards to how much I actually care about commandline.

Fido is a __UI__ script I need for Rufus. Please don't expect much more than that or you are only ever going to be disappointed.
