### ISSUE TITLE
Error: We are unable to complete your request at this time

### ISSUE THREAD

**Issue by MesterPerfect** [pbatard/Fido#55]
I'm trying to use Fido by python
It works on the first and second try
But on the third attempt

```
C:\Users\MesterPerfect\Desktop>python example.py
Error: We are unable to complete your request at this time. Some users, entities and locations are banned from using this service. For this reason, leveraging anonymous or location hiding technologies when connecting to this service is not generally allowed. If you believe that you encountered this problem in error, please try again. If the problem persists you may contact Microsoft Support â€“ Contact Us page for assistance. Refer to message code 715-123130 and 205d9517-d8ea-4f25-8406-29cf579554eb.
```

How can I avoid this problem?

**Comment by pbatard** [comment]
> How can I avoid this problem?

Don't spam the Microsoft servers, or switch you IP address (if you can do that with your internet provider), or wait a few hours.

What you describe is usually a temporary ban.

I'm afraid that, since this is a new IP filtering policy that is enacted by the Microsoft servers, there is absolutely nothing else I can advise you to do, and, especially, there is no possibility to ever be able to work around this in the script, since IP bans are applied and removed by Microsoft internally, and there is no _"unban me!"_ request that one can send.

As such, I will close this issue.
