### ISSUE TITLE
Error attempting to download non-current  Windows 10 ISO

### ISSUE THREAD

**Issue by wdouglascampbell** [pbatard/Fido#67]
Two days ago on May 11, 2023, I successfully used Fido to download the 20H1 Windows 10 ISO.  Yesterday and today I have retried from multiple machines from more than one IP address but Fido fails after clicking Continue after selecting the Language.  At this point I receive the following error.

`Error: We encountered a problem processing your request. Please try again later. 7559621b-ed6a-4f48-b1e4-07a087283434.`

**Comment by pbatard** [comment]
Yeah, I can replicate that issue.

It appears that Microsoft decided that they would only honour the request for current versions of Windows, and not for older versions.

Ultimately, since we are querying Microsoft servers and are therefore dependent on what Microsoft is actually willing to serve, if they have decided to to remove the ability to download anything but the most recent release for each version of Windows, then that's what we're going to have to go with in Fido as well.

I'm going to wait a few days to see if it's a transient error (not really hopeful about that, since Microsoft also took actions to remove the Windows 7 ISO downloads they used to provide) and if not, I will remove the older ISO downloads from Fido as well.
