### ISSUE TITLE
Error: The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by SirFrostingham** [pbatard/Fido#77]
Hi, I'm curious what this means?  Error: The underlying connection was closed: An unexpected error occurred on a send.

Steps:
1. Run **cmd** as admin
2. Run **powershell**
3. Run **.\Fido.ps1**
4. Select settings in pop-up window:
<img width="278" alt="image" src="https://github.com/pbatard/Fido/assets/4725943/46aa3e7e-8700-4b34-bdef-efffc9b9317d">

5. Click **Continue**

Result:
`
Please Wait...
Querying https://www.microsoft.com/en-US/software-download/
Querying https://vlscppe.microsoft.com/tags?org_id=y6jn8c31&session_id=9f613383-6194-4179-8106-9a18ee924e04
Error: The underlying connection was closed: An unexpected error occurred on a send.
`

Thank you.

**Comment by graham00** [comment]
I was getting the same error. Well, all I get was 'Error: The underlying connection was closed: An unexpected error occurred on a send.'. I tried via the UI and also via -GetUrl - same result either way.

I tried it behind a different internet connection however and it worked.

It looks like the original site crapped out while trying to pull a list of languages as that's the next step I got when I ran it behind another internet connection. I changed the VM (vmware workstation, where I try any code/etc I haven't read through and tested thoroughly) I was testing in to point its DNS to google (8.8.8.8) and flushed DNS and tried again - same result.

I then tried it on another machine under the original site's internet and it worked on that machine. Then just for the sake of thoroughness I went back to the original test VM and tried again there - still failed.

My test VM is Win10 build 1709. The same-network machine where it worked was Win10 1809 (Enterprise LTSC). I'm not saying for sure that that is necessarily the root cause, but it's the only meaningful difference I can discern.

**Comment by pbatard** [comment]
Obviously, a script that is designed to access networked servers cannot do much about issues that are intrinsics to some networks (such as ones that use firewalls to filter out internet access or other security solutions).

Considering that this is definitely not a widespread issue, but one that is affecting specific individuals, I have to dismiss it as external to Fido.
