### ISSUE TITLE
Windows 11 23H2 v2 released

### ISSUE THREAD

**Issue by ave9858** [pbatard/Fido#83]
Product IDs were added recently
2935: Windows 11 23H2_v2
2936: Windows 11 23H2_v2 Home China

Generated links don't work yet

**Comment by ave9858** [comment]
Links are now working and it has been added to https://www.microsoft.com/en-US/software-download/windows11

**Comment by pbatard** [comment]
Thanks. I'll update Fido when I get a chance.

**Comment by pbatard** [comment]
Now updated. Apologies for the delay.

**Comment by homes32** [comment]
Is there a better way to do this so we do not remove older downloads until they actually don't work? Fido v1.54 will no longer download Win11 23H2v1, even though the link is still working. (ie. M$ has not removed the ISO yet.) If I download Fido v1.53 it works fine.

Microsoft has a track record of buggering up Explorer.exe between releases so those of us running WinPE projects such as  https://github.com/PhoenixPE/PhoenixPE and https://github.com/ChrisRfr/Win10XPE often have to direct users to use a previous ISO until we can fix whatever they broke.

**Comment by pbatard** [comment]
> Is there a better way to do this so we do not remove older downloads until they actually don't work?

No, because I don't want to be caught short with people complaining that some of the downloads from Fido no longer work and it is pretty clear that Microsoft __will__ remove the 23H2v0 ISO downloads. I have no interest keeping a feature that I know is going to break, especially as I have better things to do than be on the lookout for when it breaks in order to update Fido. It's just not worth it. If you can't use the latest version of Windows released by Microsoft, it's really a problem that you need to sort out with Microsoft. They have a support department and you are __not__ going to properly solve any of your issues with Explorer unless you do make Microsoft aware of it.

**Comment by homes32** [comment]
fair enough. thanks for the reply.

**Comment by ave9858** [comment]
3113: Windows 11 24H2
3114: Windows 11 24H2 Home China
3115: Windows 11 24H2 Pro China

Generated links don't work yet

**Comment by pbatard** [comment]
Still **23H2** on https://www.microsoft.com/software-download/windows11. 24H2 cannot be proposed until Microsoft provides 24H2 downloads on the URL above.

**Comment by ave9858** [comment]
> As far as i know, 24H2 is currently ONLY avalable on ARM devices with specific CPUs (not counting insider builds)

ISOs were uploaded, so GA ISOs can be downloaded now using the IDs posted above.

**Comment by ave9858** [comment]
> Still **23H2** on https://www.microsoft.com/software-download/windows11. 24H2 cannot be proposed until Microsoft provides 24H2 downloads on the URL above. But thanks for the ID numbers.

24H2 is now listed at https://www.microsoft.com/en-us/software-download/windows11

**Comment by pbatard** [comment]
Fido has now been updated to provide the Windows 11 24H2 ISO downloads.

**Comment by ave9858** [comment]
2935 and 2936 seem dead now, can't generate any more links

**Comment by pbatard** [comment]
Yup, I see that too. Microsoft sure didn't lose any time removing any trace of 23H2 from the face of the earth... I'll update Fido to remove these as well.

**Comment by ave9858** [comment]
3131: Windows 11 Arm64 24H2
3132: Windows 11 Arm64 24H2 Home China
3133: Windows 11 Arm64 24H2 Pro China

Links can be generated but ISOs are not uploaded to the backend yet

**Comment by pbatard** [comment]
Heh? Microsoft is **FINALLY** going to make ARM64 ISOs **publicly** available (after about 3 years of indicating that they would). Wow, that was fast...

Thanks a lot for the IDs. I'll update Fido once they become available.

**Comment by ave9858** [comment]
https://software.download.prss.microsoft.com/dbazure/Win11_24H2_English_Arm64.iso?t=5e826385-073f-45f2-a5e2-1bb12bb8614d&P1=1731635598&P2=601&P3=2&P4=Xg7sGgsxwubWdS%2f03xqFIItWLx6IvVElQ8j0uAlca4briGFn5TBI6e2TJYDWpPiTRhKG1KpBBXseaoN%2bQKlTQjVoiabeJdmqYub6bI8Y3odlbhKn8b95icZUZgXD%2fNqCdGA15OYnb0eiu97NYef%2f1h6C8Hr7q1BLEwGj8WPoE5k7osZtwyWhyxchjQF%2btjJO1tCLhwOxbWity3CFG6iXfcOCMPBPo%2ba3awPW9ECi6vxZl7oc7We2zTxTVSp7jcMtDJts4Pj%2fipxGkuyzg%2f17OFUOqLTj3sVGfiTnFq5iqX7LGITMfoIKcdssOC1VE%2fFBeh%2fOdAVEPh0Wx8YB22vOcA%3d%3d

ARM64 download links are working now

**Comment by pbatard** [comment]
Yeah, that's actually gonna be a pain to add to Fido (in an elegant manner), because whereas Microsoft did use the same SKU for x86 and x64 download, and just broke them down by arch, they suddenly decided to drop this for ARM64, instead of just reusing the same thing an adding the extra arch on the relevant SKU.

Well, whatever new moronic thing Microsoft decides to do, I'd prefer to have Fido not to be that counter-intuitive and provide the ARM64 download along with the x64 Win11 download, by simply switching the arch there, **AS IT SHOULD BE**, so this is going to require some creative reworking of the script to fetch both the ARM64 and x64 SKUs at once, to make them available at the same time...

**Comment by pbatard** [comment]
ARM64 ISO download support has now been added in the [latest release of Fido](https://github.com/pbatard/Fido/releases).
As indicated above, this is added in Fido as a regular arch entry rather than as Microsoft utterly moronic separate SKU.

Please test and, if you do find a problem, report it **by creating a new issue** (rather than adding to this lengthy thread). Thank you.
