### ISSUE TITLE
Add support for downloading Media Creation Tool ESDs

### ISSUE THREAD

**Issue by driver1998** [pbatard/Fido#86]
As the name suggests, these are the files actually downloaded by the Media Creation Tool.

Some valid points: 
- These are all-in-one, with all the contents you need in one file, and can be used to build ISOs with minimal effort (unlike UUP fileset where you'll need to guess or hack around some stuff).
- Or if you just want to install the OS, apply image 4 is all you need, no conversion required.
- The file list MCT downloads contains all languages and includes SHA-1 hash for each file.
- This is the only way to download official ARM64 installation media from Microsoft (for free that is, too bad MCT does not have any UI for it).

How to get the file list with MCT:
- Run MCT of the desired version (10 or 11)
- When the EULA shows up, go to `C:\$Windows.~WS\Sources`, you should see `products.cab`, extract it to get `product.xml` (MCT might already did this)
- Open the file to get all the ESD files link and their SHA-1 hash.

```xml
<MCT>
  <Catalogs>
    <Catalog version="1.4.1">
      <PublishedMedia id="" release="">
        <Files>
          <File id="">
            <FileName>19045.3803.231204-0204.22h2_release_svc_refresh_CLIENTCONSUMER_RET_A64FRE_zh-cn.esd</FileName>
            <LanguageCode>zh-cn</LanguageCode>
            <Language>Chinese (Simplified, China)</Language>
            <Edition>Core</Edition>
            <Architecture>ARM64</Architecture>
            <Size>3819160148</Size>
            <Sha1>296d7f8361ba34db797b8ffd29496ecd36dacb27</Sha1>
            <FilePath>http://dl.delivery.mp.microsoft.com/filestreamingservice/files/bd6b5fe4-348a-4fb1-97e9-297c9136dfc2/19045.3803.231204-0204.22h2_release_svc_refresh_CLIENTCONSUMER_RET_A64FRE_zh-cn.esd</FilePath>
            <Key />
            <Architecture_Loc>%ARCH_64%</Architecture_Loc>
            <Edition_Loc>%CLIENT%</Edition_Loc>
            <IsRetailOnly>True</IsRetailOnly>
          </File>
        </Files>
      </PublishedMedia>
    </Catalog>
  </Catalogs>
</MCT>
```

MCT ESD layout: 
```plaintext
Image 1:  Windows Setup Media (All the files on the ISO, except WIMs)
Image 2:  boot.wim Image 1
Image 3:  boot.wim Image 2
Image 4+: install.wim Images
```

**Comment by pbatard** [comment]
> and can be used to build ISOs with minimal effort

But why, when you can download the full ISOs, and, as opposed to ESB built ISOs, [they can be formally validated](https://github.com/pbatard/rufus/wiki/FAQ#user-content-How_can_I_validate_that_a_Windows_ISO_is_a_genuine_retail_version). Even if you can validate the SHA-1 of the individual components, it doesn't remove the fact that people still need to trust the script, whereas, in its current form, people who don't trust the script can easily validate that it's not doing anything dodgy.

If I were to add ISO from ESD in Fido, I'm pretty sure I'd get quite a few of _"Because your script is creating ISOs that can't be formally validated, how can we be sure that Fido is not injecting malware into the resulting ISO?"_.

I will also very much dispute the "minimal effort", which looks like something someone, who doesn't have to perform the task themselves, and especially will not have to support it __for years thereafter__, would say. _Anything you don't have to do yourself looks like a 5 minutes job_.

> This is the only way to download official ARM64 installation media from Microsoft

Then complain to Microsoft that they need to release official ISOs for ARM64, like they should have done a long time ago.

There's really no point of adding another route to get from point A to point B when you already have a perfectly suitable road, and I have zero time to inject in what a don't consider to be a needed endeavour. &rarr; Rejected.
