### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by azmeeridz** [pbatard/Fido#89]
Hi,

I have try both GUI and command line unfortunately both came out with same error, even with using different ISPs

![Screenshot 2024-02-08 214031](https://github.com/pbatard/Fido/assets/106534883/71e62c9a-b993-4564-85ee-04501f2833b5)

![Screenshot 2024-02-08 210135](https://github.com/pbatard/Fido/assets/106534883/29d36a9c-8f2b-4467-8e36-5c39f7568967)

**Comment by azmeeridz** [comment]
I am using Windows 11 Pro 23H2 and i had tested the script on another machine with Windows 10 Pro 22H2 both showing the same error. My network shouldn't have any issues as i had downloaded the iso direct from MSFT website successfully

**Comment by pbatard** [comment]
Well, you're the only person reporting this and, since Fido is tied to Rufus, there are literally thousands of people who appear to be using the current script without issue (as they would definitely report something otherwise), so your issue does appear to be linked to your environment or network.

Please also bear in mind that Microsoft deliberately filters IP addresses and sometimes whole IP regions they don't like, so it could be regional filter on Microsoft's part.

You may also want to double check that you download the script again, if you happened to have downloaded it yesterday, as I did a double push of version 1.55 to work around the latest MS server restrictions, so please delete the script, download it again, and see if the issue still happens
