### ISSUE TITLE
Error: Could not parse languages

### ISSUE THREAD

**Issue by Joly0** [pbatard/Fido#91]
![grafik](https://github.com/pbatard/Fido/assets/13993216/fd76e58d-756f-4690-be11-ff098550b60c)
Not sure what this means, as one can see, i selected Windows 10 22H2 with the Home/Pro/Edu edition and then the error showed up. I am using a german OS if that is useful information.

**Comment by Joly0** [comment]
Also same when i try to use the manual commands ".\Fido.ps1 -Win 10 -Rel Latest -Lang German" or ".\Fido.ps1 -Win 10 -Rel Latest -Lang Deutsch" and even with ".\Fido.ps1 -Win 10 -Rel Latest -Lang English".

And another thing i noticed, is that i only can see 22H2 v1 as an option for the release, per your documentation, i should have alot more options?

**Comment by Joly0** [comment]
Also for ".\Fido.ps1 -Win 11 -Rel List" my only output is 
```
Please select a Windows Release (-Rel) for Windows 11 (or use 'Latest' for most recent):
 - 23H2 v2 (Build 22631.2861 - 2023.12)
```

**Comment by pbatard** [comment]
Not seeing the issue on my end.

Please be aware that, as with any networked application, if you have a firewall or a network issue somewhere up the line (or if, as is a common occurrence, Microsoft's own server firewalls decided that they don't like you), then the application will produce an error, but it will have nothing to do with the application, nor will it be something that can (and should) be fixed by the application.

The issue appears to be purely on your side I'm afraid.

**Comment by Chucky2401** [comment]
Same issue here
![image](https://github.com/pbatard/Fido/assets/53853245/4d21d9e8-fab4-42f5-b724-b9fdb73d0ca1)

I can access this URL: https://www.microsoft.com/fr-FR/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,windows11&query=&action=getskuinformationbyproductedition&sessionId=a7afe8e9-639e-4694-b461-68268e73a4d1&productEditionId=2935&sdVersion=2.

But when I click on Confirm, nothing happens

**Comment by scriptingstudio** [comment]
This is just a guess.
Message `built-in manual was disabled at build-time` may indicate that it is Linux env. The script uses `curl` command in the code which is an alias for `Invoke-WebRequest`. Would it better to use explicit command rather than alias?

**Comment by Joly0** [comment]
> This is just a guess. Message `built-in manual was disabled at build-time` may indicate that it is Linux env. The script uses `curl` command in the code which is an alias for `Invoke-WebRequest`. Would it better to use explicit command rather than alias?

1. Yes, imo it would make sense to replace curl with Invoke-WebRequest
2. I have this message `built-in manual was disabled at build-time` aswell, and i am running on windows, not linux

**Comment by Joly0** [comment]
Btw, i also got this link when trying to download:
https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,windows11&query=&action=getskuinformationbyproductedition&sessionId=30ba363b-5d68-4f08-a589-8f35beb21432&productEditionId=2935&sdVersion=2

When i go to that page manually, i get this:
![grafik](https://github.com/pbatard/Fido/assets/13993216/665ba630-9e9a-49ef-96cc-f4e035ae043e)
And when i try to select a language and click confirm, nothing happens. I know this is a microsoft site and has nothing to do with your tool, but it might be helpful information to identify the issue of this problem?

Also, is there a reason i only see 23H2 or Windows 11 Home/Pro/Edu as my only options when downloading a windows 11 iso? Same for Windows 10 or so, i only get the latest available option. No other options.

**Comment by pbatard** [comment]
@Joly0, you see the dynamic content that is being queried by the page. Those are **not** meant to be regular web pages that you can interact with, so, of course, nothing will happen. It's basically the bricks that are constructing the page you see at https://www.microsoft.com/en-US/software-download/windows11 as you interact with it, and not the full house that is being displayed by the web browser.

And the reason you only see latest is that, since we can only download what Microsoft provides publicly on their server, and earlier this year Microsoft removed access to ALL of the older Windows versions, we can no longer provide access to them through Fido.

As to why we use the `curl` alias rather than `Invoke-WebRequest`, this is because Microsoft also stepped up their anti-script  measures this year, and we are expecting to have to use actual `curl` (i.e. not the `Invoke-WebRequest` alias) at some stage, when Microsoft steps up their game. We used to have `Invoke-WebRequest` before, but `Invoke-WebRequest` is super limited compared to `curl`, so we are moving towards formal use of `curl` even, and this may be your issue, if you do use actual `curl` with the current script, you may very well run into the issue above. As  a matter of fact, the fact that you get `warning: built-in manual was disabled at build-time` seems to indicate that you are in fact using actual `curl` rather than the alias.

However, I'm not planning to look into switching to actual `curl` until it becomes necessary (though I'll accept a patch that both disables the `curl` alias for `Invoke-WebRequest` and sorts parsing from `curl` returned data), so for the time being, I will ask you to sort your curl alias issues on your own, as the expectation is that your PowerShell should still alias `curl` to `Invoke-WebRequest`.

**Comment by 1000TurquoisePogs** [comment]
I encounter this when using powershell 7, but not when using builtin powershell of windows 10.

**Comment by Chucky2401** [comment]
> I encounter this when using powershell 7, but not when using builtin powershell of windows 10.

I confirm. Works in PowerShell 5.1 unlike 7+

**Comment by pbatard** [comment]
Okay. If that is the case, I may revert to using `Invoke-WebRequest` instead of `curl` since I expect this should sort things out and I have no idea when I'll get a chance to switch to formal `curl` (and I'll have to specify `curl.exe` rather than `curl` in the script anyway to ensure that we don't use the alias).
