### ISSUE TITLE
New JSON-based API

### ISSUE THREAD

**Issue by ave9858** [pbatard/Fido#98]
The official software download pages are now using a new API, which works similarly to the old API but returns JSON instead of HTML. Example URL `https://www.microsoft.com/software-download-connector/api/getskuinformationbyproductedition?profile=606624d44113&ProductEditionId=3113&SKU=undefined&friendlyFileName=undefined&Locale=en-US&sessionID=` (add valid sessionID, generated same as before). It seems like the old API might eventually be shut down, insider ISO links already can't be generated using the old API in my testing.

**Comment by pbatard** [comment]
Thanks for the heads up. I must admit I did not bother to look at how the software download page produced its responses when adding ARM64, as the existing method worked fine and I can indeed see that the website is responding in JSON rather than HTML by default now. This might not be a bad thing, since I am actually converting the HTML to XML and then to JSON in Fido to process it, so this could simplify things, though it may make reporting the [Code 715-123130 error](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO) error more problematic if we don't get an HTML error message we can pass back to the user...

And there I thought I was done with updating Fido after the ARM64 update... &lt;sigh&gt;

**Comment by ave9858** [comment]
> though it may make reporting the [Code 715-123130 error](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO) error more problematic if we don't get an HTML error message we can pass back to the user...

seems like that error is replaced with ErrorSettings.SentinelReject/"Sentinel marked this request as rejected.", so you could either report that directly to the user (probably quite confusing) or just include your own string to report the error when you see that error response.

**Comment by pbatard** [comment]
> Edit: localization might be a problem

Yeah. That's the reason why I'd rather parse the answer from MS, since it's localized. I'll look at other options, such as the one you suggest, but it looks like we may have to add a new localized error message in Rufus (which will then pass it on to Fido) for that error.

Or I may just copy the various localized HTML errors from MS, upload them somewhere on a static GitHub website, and download that from a fixed URL, so that the error reported to the users, which provides a good explanation of the rejection, will remain the same and so that I don't have to add/edit the FAQ.

**Comment by ave9858** [comment]
One more error I found when updating my python library was key `ErrorSettings.GenericError` and value `Unhandled error`, it seems to be a server-side error since I couldn't reproduce it at all and I've only seen it once. I'd suggest retrying the request or ignoring since it seems to have a less than 1% chance of happening.

**Comment by pbatard** [comment]
Well, I'm afraid that there's more going on now (in terms of filtering out scripts) than simply hitting `vlscppe.microsoft.com` with the session ID and then issuing the requests to the new JSON API. Yet again, Microsoft have ramped up their anti-script protection, and if you do the usual dance (and even if you add the extra https://vlscppe.microsoft.com/tags.js and https://ov-df.microsoft.com/mdt.js requests with the session ID), you just end up with `405` or `403` errors when querying https://www.microsoft.com/software-download-connector/.

Did you really manage to make the public download webpage work with your python library? If so, do you have a pointer to your changes? I had a quick look at https://github.com/ave9858/mvs-dump/commits/master/ which I assume is the python library you are talking about, but it seems to be for subscriber downloads and not public ones...

**Comment by ave9858** [comment]
> Did you really manage to make the public download webpage work with your python library? If so, do you have a pointer to your changes? I had a quick look at https://github.com/ave9858/mvs-dump/commits/master/ which I assume is the python library you are talking about, but it seems to be for subscriber downloads and not public ones...

The python library isn't public since its mainly used for internal stuff and the MSDL API. I can send the code to you privately or maybe open source it after checking with the team. I wasn't aware of any changes to filter out scripts, checking now.

**Comment by ave9858** [comment]
![image](https://github.com/user-attachments/assets/91318b6d-e5b7-4a27-a24f-6c4e782427cb)
Here's the relevant code for the non-proxy version, will check if it still works in a moment

**Comment by pbatard** [comment]
here's what I'm currently getting (regardless of whether I add or remove the extra .js requests):
```
PS D:\Projects\Fido> .\Fido.ps1 -Debug
Please Wait...
Querying https://www.microsoft.com/en-US/software-download/windows11
Querying https://vlscppe.microsoft.com/tags?org_id=y6jn8c31&session_id=3ba9abe6-5055-40c8-bfbd-579233c727f4
Querying https://vlscppe.microsoft.com/tags.js?org_id=y6jn8c31&session_id=3ba9abe6-5055-40c8-bfbd-579233c727f4
Querying https://ov-df.microsoft.com/mdt.js?instanceId=3540d1d7-3513-4ec3-b52a-a8617733a58c&pageId=si&session_id=3ba9abe6-5055-40c8-bfbd-579233c727f4
Querying https://www.microsoft.com/software-download-connector/api/getskuinformationbyproductedition?profile=606624d44113&productEditionId=3113&SKU=undefined&friendlyFileName=undefined&Locale=en-US&sessionID=3ba9abe6-5055-40c8-bfbd-579233c727f4
Error: The remote server returned an error: (403) Forbidden.
```

When testing from the webpage, the `getskuinformationbyproductedition` request works as expected, so my IP is definitely not being filtered out as would be the case with the code 715-123130 error.

Further testing shows that the issue is with the `-UseBasicParsing`. If `-UseBasicParsing` is removed, then the query works... but this creates issue because this require the IE engine to have been installed, and this is being removed from newer PowerShell versions and even if supported, you have to go through an extra prompt on first time use IIRC.

Looks like we may have to switch to using `curl.exe` because of this, [which I kind of anticpated we might have to do some time ago](https://github.com/pbatard/Fido/issues/91#issuecomment-2156813508), but which will probably shut down older platforms, like Windows 8 or Windows 10 from being able to run Fido...

But at least, in part thanks to your help, I have been able to find out why the request failed. It figures that Microsoft would use their own crippling of their PowerShell web engine as a means to detect that they should not serve content to it...

**Comment by ave9858** [comment]
Weird, I'm able to do the requests fine in Powershell

**Comment by pbatard** [comment]
Strange. And I may have spoken too soon about `-UseBasicParsing` because now, even if I don't use the flag, I'm running into `403` again, despite running the exact same PS code that worked twice before. Even trying from a different machine, and a different IP, I'm getting the `403` for the PS code that worked.

I think there's definitely some anti-script detection going on there, which might be a bit less obvious than what Microsoft used to do (especially as the very first error code I got when starting to test was `Error: The remote server returned an error: (405) Method Not Allowed.` and then, when retrying the same thing, I only got `403`'s...

**Comment by pbatard** [comment]
Issuing:
```
Invoke-WebRequest "https://vlscppe.microsoft.com/tags?org_id=y6jn8c31&session_id=3ba9abe6-5055-40c8-bfbd-579233c727f4"
Invoke-WebRequest "https://www.microsoft.com/software-download-connector/api/getskuinformationbyproductedition?profile=606624d44113&productEditionId=3113&SKU=undefined&friendlyFileName=undefined&Locale=en-US&sessionID=3ba9abe6-5055-40c8-bfbd-579233c727f4"
```
from the commandline does appear to work fine though, so maybe it has to do with Microsoft validating the User-Agent further, since I guess our use of partially random data for it could be detectable (and explain why it might work randomly as well).

I'll continue to look into this...

**Comment by pbatard** [comment]
Yeah, it's the same `Invoke-WebRequest` code from current Fido, which is basically:
```
Invoke-WebRequest -UseBasicParsing -TimeoutSec $DefaultTimeout -UserAgent $UserAgent -SessionVariable "Session" $url
```
I tried playing with GET/POST methods, in case it matters, and as explained earlier, with `UseBasicParsing` (which actually works fine from commandline), which doesn't leave much between the custom User Agent or possibly some of the queries to the main MS download page we issue before hand.

**Comment by pbatard** [comment]
Yup, removing all the business we do with the User Agent appears to make the script work now. Tried it 4 times now, and no more errors.

Wow, Microsoft really have wasted even more time than they did at the beginning of the year, looking at our script and trying to filter us out explicitly (and in doing so, apparently removed the filtering that had forced us to use a custom User-Agent in the first place). This is such a stupid cat and mouse game...

**Comment by ave9858** [comment]
Yeah, that's why I'm worried about releasing the python script publicly, it could cause Microsoft to block it more often if it ends up being used in a project they don't like.

**Comment by pbatard** [comment]
I have now switched Fido to use the new MS JSON API. We'll just have to see how long Microsoft takes to try to filter it out again...
